1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/urls.py
from django.urls import path
from . import views

app_name = 'eithers'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:question_pk>/', views.detail, name='detail'),
    path('random/', views.random, name='random'),
    path('<int:question_pk>/comment/', views.comment_create, name='comment_create'),
]

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/models.py
from django.db import models


class Question(models.Model):
    title = models.CharField(max_length=200)
    issue_a = models.CharField(max_length=100)
    issue_b = models.CharField(max_length=100)


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.BooleanField()
    content = models.CharField(max_length=100)

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/forms.py
# eithers/forms.py

from django import forms
from .models import Question, Comment

class QuestionForm(forms.ModelForm):
    issue_a = forms.CharField(label="RED TEAM")
    issue_b = forms.CharField(label="BLUE TEAM")
    class Meta:
        model = Question
        fields = '__all__'



class CommentForm(forms.ModelForm):
    PICK_A = False
    PICK_B = True
    PICKS = [
        (PICK_A, 'RED TEAM'),
        (PICK_B, 'BLUE TEAM'),
    ]
    pick = forms.ChoiceField(choices=PICKS, widget=forms.Select())
    
    class Meta:
        model = Comment
        fields = ['pick', 'content']

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Question
from .forms import QuestionForm, CommentForm

def index(request):
    questions = Question.objects.order_by('-pk')
    context = {
        'questions': questions,
    }
    return render(request, 'eithers/index.html', context)


def create(request):
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        if question_form.is_valid():
            question = question_form.save()
            return redirect('eithers:index')
    else:
        question_form = QuestionForm()
    context = {
        'question_form': question_form,
    }
    return render(request, 'eithers/create.html', context)


def detail(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)

    comment_form = CommentForm()
    context = {
        'question': question,
        'comment_form': comment_form,
    }
    return render(request, 'eithers/detail.html', context)


def random(request):
    import random

    pk_list = []
    for value in Question.objects.values('pk'):
        pk_list.append(value['pk'])
    random_pk=random.choice(pk_list)
    
    return redirect('eithers:detail', random_pk)


def comment_create(request, question_pk):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.question_id = question_pk
            comment.save()
    return redirect('eithers:detail', question_pk)

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/templates/eithers/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<a href="{% url 'eithers:index' %}">BACK</a>
<hr>
<form action="" method="POST">
  {% csrf_token %}
  {{ question_form.as_p }}
  <button>Create</button>
</form>
{% endblock  %}

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/templates/eithers/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<hr>
<h2>{{ question.title }}</h2>
<div>
  <h4>Red TEAM <h5> => {{ question.issue_a }}</h5></h4>
  <br>
  <h4>Blue TEAM <h5> => {{ question.issue_b }}</h5></h4>
</div>
<hr>
<a href="{% url 'eithers:index' %}">BACK</a>
<hr>

<h3>댓글 작성</h3>
<form action="{% url 'eithers:comment_create' question.pk %}" method="post">
  {% csrf_token %}
  {{ comment_form.as_p }}
  <button type="submit">작성</button>
</form>

<hr>

<h3>댓글 목록</h3>
{% for comment in question.comment_set.all %}
  {% if comment.pick %}
    <p>Blue - {{ comment.content }}</p>
    {% else %}
    <p>Red - {{ comment.content }}</p>
  {% endif %}
{% empty %}
  <h4>아직 의견이 없습니다 :(</h4>
{% endfor %}
{% endblock  %}

1006_실습/실습실 과제/데일리+실습_db_03_4_P/eithers/templates/eithers/index.html
{% extends 'base.html' %}

{% block content %}
<h1>INDEX</h1>
<hr>
{% for question in questions %}
  <div>
    <p>{{ forloop.counter }}번 이슈</p>
    <h2>{{ question.title }}</h2>
    <a href="{% url 'eithers:detail' question.pk %}">DETAIL</a>
  </div>
  <hr>
{% endfor %}
{% endblock  %}